import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/database/client";
import { costs, inventoryItems, listings, opportunities, sales } from "@/database/schema";
import { addCost, addListing, sellItem } from "@/features/inventory/actions";
import { requireUser } from "@/lib/auth/session";
import { formatBRL } from "@/lib/money";
const today=new Date().toISOString().slice(0,10);
export default async function InventoryDetail({params}:{params:Promise<{id:string}>}){const user=await requireUser(),{id}=await params,row=await db.select({item:inventoryItems,opportunity:opportunities}).from(inventoryItems).innerJoin(opportunities,eq(inventoryItems.opportunityId,opportunities.id)).where(and(eq(inventoryItems.id,id),eq(inventoryItems.userId,user.userId))).get();if(!row)notFound();const itemCosts=await db.select().from(costs).where(eq(costs.inventoryItemId,id)).all(),itemListings=await db.select().from(listings).where(eq(listings.inventoryItemId,id)).all(),sale=await db.select().from(sales).where(eq(sales.inventoryItemId,id)).get();const profit=sale?sale.receivedCents-row.item.actualCostCents:null;return <div className="grid gap-6"><header><a href="/estoque" className="text-sm text-[var(--muted)]">← Estoque</a><h1 className="mt-2 text-3xl font-black">{row.opportunity.title}</h1><p className="text-sm text-[var(--muted)]">{row.item.status.replaceAll("_"," ")} · adquirido em {new Date(row.item.acquiredAt).toLocaleDateString("pt-BR")}</p></header>
  <section className="grid gap-4 sm:grid-cols-3"><article className="panel p-4"><p className="text-xs font-bold text-[var(--muted)]">CUSTO REAL</p><p className="mt-2 text-2xl font-black">{formatBRL(row.item.actualCostCents)}</p></article><article className="panel p-4"><p className="text-xs font-bold text-[var(--muted)]">VALOR RECEBIDO</p><p className="mt-2 text-2xl font-black">{sale?formatBRL(sale.receivedCents):"—"}</p></article><article className="panel p-4"><p className="text-xs font-bold text-[var(--muted)]">LUCRO REAL</p><p className={`mt-2 text-2xl font-black ${(profit??0)>=0?"text-moss dark:text-lime":"text-clay"}`}>{profit==null?"Não vendido":formatBRL(profit)}</p></article></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="panel p-5"><h2 className="text-xl font-black">Gastos adicionais</h2>{itemCosts.length>0&&<ul className="my-4 divide-y divide-[var(--border)]">{itemCosts.map(c=><li key={c.id} className="flex justify-between py-2 text-sm"><span>{c.description} <small className="text-[var(--muted)]">({c.type})</small></span><b>{formatBRL(c.amountCents)}</b></li>)}</ul>} {row.item.status!=="VENDIDO"&&<form action={addCost} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="inventoryItemId" value={id}/><div className="field"><label>Tipo</label><select name="type"><option>REPARO</option><option>PECA</option><option>FRETE</option><option>COMBUSTIVEL</option><option>LIMPEZA</option><option>EMBALAGEM</option><option>OUTRA_DESPESA</option></select></div><div className="field"><label>Valor</label><input className="input" name="amount" required/></div><div className="field"><label>Descrição</label><input className="input" name="description" required/></div><div className="field"><label>Data</label><input className="input" type="date" name="incurredAt" defaultValue={today} required/></div><button className="button sm:col-span-2">Registrar gasto</button></form>}</div>
  <div className="panel p-5"><h2 className="text-xl font-black">Anúncios próprios</h2>{itemListings.length>0&&<ul className="my-4 divide-y divide-[var(--border)]">{itemListings.map(l=><li key={l.id} className="flex justify-between py-2 text-sm"><span>{l.source} · {l.status}</span><b>{formatBRL(l.currentPriceCents)}</b></li>)}</ul>}{row.item.status!=="VENDIDO"&&<form action={addListing} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="inventoryItemId" value={id}/><div className="field"><label>Plataforma</label><select name="source"><option>Facebook Marketplace</option><option>OLX</option><option>Mercado Livre</option><option>Outra</option></select></div><div className="field"><label>Preço anunciado</label><input className="input" name="price" required/></div><div className="field"><label>URL</label><input className="input" name="url" type="url"/></div><div className="field"><label>Data</label><input className="input" name="listedAt" type="date" defaultValue={today} required/></div><button className="button sm:col-span-2">Registrar anúncio</button></form>}</div></section>
  {!sale&&<section className="panel p-5"><h2 className="text-xl font-black">Registrar venda</h2><p className="text-sm text-[var(--muted)]">Informe custos da venda separadamente; o sistema preserva o valor anunciado e calcula o líquido.</p><form action={sellItem} className="mt-4 grid gap-3 sm:grid-cols-3"><input type="hidden" name="inventoryItemId" value={id}/>{[['salePrice','Preço de venda'],['platformFee','Taxa da plataforma'],['sellerShipping','Frete pago pelo vendedor'],['discount','Desconto negociado'],['taxes','Impostos informados'],['otherSaleCosts','Outros custos']].map(([n,l])=><div className="field" key={n}><label>{l}</label><input className="input" name={n} required={n==='salePrice'} defaultValue={n==='salePrice'?undefined:'0,00'}/></div>)}<div className="field"><label>Pagamento</label><select name="paymentMethod"><option>PIX</option><option>DINHEIRO</option><option>CARTAO</option><option>TRANSFERENCIA</option><option>OUTRO</option></select></div><div className="field"><label>Data da venda</label><input className="input" name="soldAt" type="date" defaultValue={today} required/></div><div className="field"><label>Comprador (apelido opcional)</label><input className="input" name="buyerAlias"/></div><div className="field"><label>Garantia combinada até</label><input className="input" name="warrantyUntil" type="date"/></div><div className="sm:col-span-3"><button className="button">Concluir venda</button></div></form></section>}
  </div>}
