import Link from "next/link";
import { and, eq } from "drizzle-orm";
import { db } from "@/database/client";
import { inventoryItems, ledgerEntries, opportunities, sales } from "@/database/schema";
import { MetricCard } from "@/components/metric-card";
import { EmptyState } from "@/components/empty-state";
import { requireUser } from "@/lib/auth/session";
import { formatBRL, formatPercent } from "@/lib/money";

export default async function Dashboard(){const user=await requireUser(),ops=await db.select().from(opportunities).where(eq(opportunities.userId,user.userId)).all(),inventory=await db.select().from(inventoryItems).where(eq(inventoryItems.userId,user.userId)).all(),ledger=await db.select().from(ledgerEntries).where(eq(ledgerEntries.userId,user.userId)).all(),sold=await db.select({sale:sales,item:inventoryItems,opportunity:opportunities}).from(sales).innerJoin(inventoryItems,eq(sales.inventoryItemId,inventoryItems.id)).innerJoin(opportunities,eq(inventoryItems.opportunityId,opportunities.id)).where(eq(inventoryItems.userId,user.userId)).all();const entries=ledger.filter(e=>e.direction==="ENTRADA"&&e.settledAt).reduce((a,b)=>a+b.amountCents,0),exits=ledger.filter(e=>e.direction==="SAIDA"&&e.settledAt).reduce((a,b)=>a+b.amountCents,0),invested=inventory.filter(i=>i.status!=="VENDIDO").reduce((a,b)=>a+b.actualCostCents,0),profit=sold.reduce((a,r)=>a+r.sale.receivedCents-r.item.actualCostCents,0),avgRoi=sold.length?sold.reduce((a,r)=>a+((r.sale.receivedCents-r.item.actualCostCents)/r.item.actualCostCents)*100,0)/sold.length:0,avgDays=sold.length?Math.round(sold.reduce((a,r)=>a+(new Date(r.sale.soldAt).getTime()-new Date(r.item.acquiredAt).getTime())/86400000,0)/sold.length):0;const monthMap=new Map<string,{in:number,out:number}>();for(const e of ledger){const key=e.occurredAt.slice(0,7),v=monthMap.get(key)??{in:0,out:0};v[e.direction==="ENTRADA"?"in":"out"]+=e.amountCents;monthMap.set(key,v)}const months=[...monthMap.entries()].sort().slice(-6),max=Math.max(1,...months.flatMap(([,v])=>[v.in,v.out]));return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-moss dark:text-lime">VISÃO DO NEGÓCIO</p><h1 className="text-3xl font-black">Seu brique, nos números.</h1><p className="text-sm text-[var(--muted)]">Valores recebidos e pagos, sem confundir anúncio com venda.</p></div><Link className="button" href="/oportunidades/nova">Analisar oportunidade</Link></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Saldo de caixa" value={formatBRL(entries-exits)} note="Lançamentos liquidados"/><MetricCard label="Capital em estoque" value={formatBRL(invested)} tone="warn"/><MetricCard label="Receita recebida" value={formatBRL(entries)} /><MetricCard label="Lucro realizado" value={formatBRL(profit)} tone="good"/><MetricCard label="Em análise" value={String(ops.filter(o=>o.status==="EM_ANALISE").length)}/><MetricCard label="Itens comprados" value={String(inventory.length)}/><MetricCard label="Anunciados" value={String(inventory.filter(i=>i.status==="ANUNCIADO").length)}/><MetricCard label="Vendidos" value={String(sold.length)}/></section>
  {!ops.length?<EmptyState title="Comece por uma oportunidade real" text="Cadastre um anúncio, reúna pelo menos três comparáveis da mesma condição e veja os cenários antes de comprar." href="/oportunidades/nova" action="Cadastrar oportunidade"/>:<section className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><article className="panel p-5"><h2 className="text-xl font-black">Movimento mensal</h2><p className="text-sm text-[var(--muted)]">Entradas e saídas liquidadas</p>{months.length?<div className="mt-6 flex h-52 items-end gap-4">{months.map(([month,v])=><div className="flex flex-1 flex-col items-center gap-2" key={month}><div className="flex h-40 w-full items-end justify-center gap-1"><div className="w-1/3 rounded-t bg-moss" style={{height:`${Math.max(3,v.in/max*100)}%`}} title={`Entradas ${formatBRL(v.in)}`}/><div className="w-1/3 rounded-t bg-clay" style={{height:`${Math.max(3,v.out/max*100)}%`}} title={`Saídas ${formatBRL(v.out)}`}/></div><span className="text-xs">{month.slice(5)}/{month.slice(2,4)}</span></div>)}</div>:<p className="mt-8 text-sm text-[var(--muted)]">Ainda não há lançamentos.</p>}</article><article className="panel p-5"><h2 className="text-xl font-black">Eficiência realizada</h2><dl className="mt-5 grid gap-5"><div><dt className="text-sm text-[var(--muted)]">ROI médio</dt><dd className="text-3xl font-black">{sold.length?formatPercent(avgRoi):"—"}</dd></div><div><dt className="text-sm text-[var(--muted)]">Giro médio</dt><dd className="text-3xl font-black">{sold.length?`${avgDays} dias`:"—"}</dd></div><div><dt className="text-sm text-[var(--muted)]">Ticket médio</dt><dd className="text-3xl font-black">{sold.length?formatBRL(entries/sold.length):"—"}</dd></div></dl><p className="mt-6 text-xs text-[var(--muted)]">Amostra: {sold.length} venda(s). Evite conclusões com poucos dados.</p></article></section>}
  </div>}
