import Link from "next/link";
import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/database/client";
import { marketComparables, opportunities, riskFlags } from "@/database/schema";
import { buyOpportunity } from "@/features/inventory/actions";
import { addComparable, duplicateOpportunity, toggleComparable } from "@/features/opportunities/actions";
import { requireUser } from "@/lib/auth/session";
import { buildScenarios, maximumPurchasePrice, netRevenue } from "@/lib/finance/calculations";
import { formatBRL, formatPercent } from "@/lib/money";
import { evaluatePriceGuide, PRICE_GUIDE_UPDATED_AT } from "@/lib/price-guide";
import { recommend } from "@/lib/scoring/recommendation";
import { marketStatistics } from "@/lib/scoring/statistics";

const today=new Date().toISOString().slice(0,10);
export default async function OpportunityDetail({params}:{params:Promise<{id:string}>}){
  const user=await requireUser(), {id}=await params, item=await db.select().from(opportunities).where(and(eq(opportunities.id,id),eq(opportunities.userId,user.userId))).get(); if(!item) notFound();
  const comparables=await db.select().from(marketComparables).where(eq(marketComparables.opportunityId,id)).all(), flags=await db.select().from(riskFlags).where(eq(riskFlags.opportunityId,id)).all();
  const stats=marketStatistics(comparables), purchasePrice=item.negotiatedPriceCents??item.askingPriceCents, acquisition={purchasePriceCents:purchasePrice,travelCents:item.travelCostCents,purchaseShippingCents:item.purchaseShippingCents,partsCents:item.partsCostCents,repairCents:item.repairCostCents,cleaningCents:item.cleaningCostCents,packagingCents:item.packagingCostCents,otherPurchaseCents:item.otherPurchaseCostsCents};
  const scenarios=buildScenarios(acquisition,stats,item.expectedDaysToSell), probable=scenarios[1], baseRecommendation=recommend({comparableCount:stats.count,confidence:stats.confidence,roi:probable.roi,margin:probable.margin,riskLevel:item.riskLevel,repairRisk:item.condition==="COM_DEFEITO",fraudRisk:flags.some(f=>f.severity==="CRITICO")});
  const guide=evaluatePriceGuide({...item,askingPriceCents:purchasePrice}), recommendation=guide.blockedReasons.length?{label:"Não comprar" as const,tone:"red",reasons:guide.blockedReasons}:baseRecommendation;
  const additionalCosts=item.travelCostCents+item.purchaseShippingCents+item.partsCostCents+item.repairCostCents+item.cleaningCostCents+item.packagingCostCents+item.otherPurchaseCostsCents;
  const marketMaxPurchase=maximumPurchasePrice(netRevenue({salePriceCents:stats.medianCents}),additionalCosts,item.minimumProfitCents), effectiveMaxPurchase=stats.count?(guide.adjustedBuyMaxCents?Math.min(marketMaxPurchase,guide.adjustedBuyMaxCents):marketMaxPurchase):guide.adjustedBuyMaxCents, discount=stats.medianCents?((stats.medianCents-purchasePrice)/stats.medianCents)*100:0;
  return <div className="grid gap-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/oportunidades" className="text-sm text-[var(--muted)]">← Oportunidades</Link><h1 className="mt-2 text-3xl font-black">{item.title}</h1><p className="mt-1 text-sm text-[var(--muted)]">{item.source} · {item.city}{item.neighborhood?` / ${item.neighborhood}`:""} · {item.condition.replaceAll("_"," ")}</p></div><div className="flex gap-2">{item.originalUrl&&<a className="button secondary" href={item.originalUrl} target="_blank" rel="noreferrer">Abrir original ↗</a>}<form action={duplicateOpportunity}><input type="hidden" name="id" value={id}/><button className="button secondary">Duplicar cenário</button></form></div></header>
    {flags.length>0&&<section className="rounded-2xl border border-orange-300 bg-orange-50 p-4 text-orange-950 dark:bg-orange-950/30 dark:text-orange-100"><h2 className="font-black">Sinais de risco informados</h2><ul className="mt-2 list-disc pl-5 text-sm">{flags.map(f=><li key={f.id}>{f.description} — requer verificação; isto não confirma fraude.</li>)}</ul></section>}
    {(guide.reference||guide.blockedReasons.length>0||guide.warnings.length>0)&&<section className={`rounded-2xl border p-5 ${guide.blockedReasons.length?"border-red-300 bg-red-50 dark:bg-red-950/20":"border-lime/50 bg-lime/10"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-[var(--muted)]">Sua tabela · {new Date(`${PRICE_GUIDE_UPDATED_AT}T12:00:00`).toLocaleDateString("pt-BR")}</p><h2 className="mt-1 text-xl font-black">{guide.reference?.model??"Regra especial identificada"}</h2></div><Link className="button secondary" href="/referencias">Ver tabela completa</Link></div>{guide.reference&&<div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-[var(--muted)]">Comprar até</p><p className="text-2xl font-black text-moss dark:text-lime">{formatBRL(guide.adjustedBuyMaxCents??guide.reference.buyMaxCents)}</p></div><div><p className="text-xs text-[var(--muted)]">Venda-base</p><p className="text-2xl font-black">{formatBRL(guide.reference.saleReferenceCents)}</p></div><div><p className="text-xs text-[var(--muted)]">Margem bruta-base</p><p className="text-2xl font-black">{formatBRL(guide.reference.saleReferenceCents-(guide.adjustedBuyMaxCents??guide.reference.buyMaxCents))}</p></div></div>}{guide.reductionPercent>0&&<p className="mt-3 text-sm font-bold text-orange-800 dark:text-orange-200">Teto reduzido em {guide.reductionPercent}% pelas condições informadas.</p>}{[...guide.blockedReasons,...guide.warnings].length>0&&<ul className="mt-3 list-disc pl-5 text-sm">{[...guide.blockedReasons,...guide.warnings].map((message)=><li key={message}>{message}</li>)}</ul>}</section>}
    <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="panel p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Análise explicável</h2><span className="badge">{stats.confidence} CONFIANÇA</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{scenarios.map(s=><article className={`rounded-xl border p-4 ${s.name==="Provável"?"border-moss bg-green-50 dark:bg-green-950/20":"border-[var(--border)]"}`} key={s.name}><p className="text-xs font-bold uppercase text-[var(--muted)]">{s.name}</p><p className="mt-2 text-xl font-black">{formatBRL(s.profitCents)}</p><p className="mt-1 text-sm">Venda: {formatBRL(s.salePriceCents)}</p><p className="text-sm">ROI: {formatPercent(s.roi)}</p><p className="text-sm">Margem: {formatPercent(s.margin)}</p><p className="text-xs text-[var(--muted)]">{formatBRL(s.profitPerDayCents)}/dia estimado</p></article>)}</div><div className="mt-5 rounded-xl bg-black/[.04] p-4 dark:bg-white/[.04]"><h3 className="font-black">{recommendation.label}</h3><ul className="mt-2 list-disc pl-5 text-sm text-[var(--muted)]">{recommendation.reasons.map(r=><li key={r}>{r}</li>)}</ul></div></div>
      <aside className="panel p-5"><h2 className="text-xl font-black">Limites da compra</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-[var(--muted)]">Preço máximo recomendado</dt><dd className="text-2xl font-black text-moss dark:text-lime">{effectiveMaxPurchase!==null?formatBRL(effectiveMaxPurchase):"Aguardando dados"}</dd></div><div><dt className="text-[var(--muted)]">Capital necessário agora</dt><dd className="font-bold">{formatBRL(probable.costCents)}</dd></div><div><dt className="text-[var(--muted)]">Desconto sobre a mediana</dt><dd className="font-bold">{stats.count?formatPercent(discount):"—"}</dd></div><div><dt className="text-[var(--muted)]">Ponto de equilíbrio</dt><dd className="font-bold">{formatBRL(probable.breakEvenCents)}</dd></div></dl>{item.status==="EM_ANALISE"&&<form action={buyOpportunity} className="mt-5 grid gap-3 border-t border-[var(--border)] pt-4"><input type="hidden" name="opportunityId" value={id}/><div className="field"><label>Preço final da compra</label><input className="input" name="purchasePrice" defaultValue={(purchasePrice/100).toFixed(2).replace('.',',')} required/></div><div className="field"><label>Data</label><input className="input" name="purchasedAt" type="date" defaultValue={today} required/></div><div className="field"><label>Local no estoque</label><input className="input" name="location" placeholder="Prateleira A"/></div><button className="button">Registrar compra</button></form>}</aside></section>
    <section className="panel p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Comparáveis de mercado</h2><p className="text-sm text-[var(--muted)]">{stats.count} selecionados · mediana {formatBRL(stats.medianCents)} · Q1 {formatBRL(stats.q1Cents)} · Q3 {formatBRL(stats.q3Cents)} · dispersão {formatBRL(stats.standardDeviationCents)} · idade média {stats.averageAgeDays} dias</p></div><span className="text-xs text-[var(--muted)]">Preço anunciado ≠ venda confirmada</span></div>
      {comparables.length>0&&<div className="mt-4 overflow-x-auto"><table><thead><tr><th>Usar</th><th>Anúncio</th><th>Preço</th><th>Tipo</th><th>Condição</th></tr></thead><tbody>{comparables.map(c=><tr key={c.id}><td><form action={toggleComparable}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="opportunityId" value={id}/><input type="hidden" name="included" value={String(c.included)}/><button aria-label="Alternar inclusão" className="button secondary py-1">{c.included?"✓":"—"}</button></form></td><td><p className="font-bold">{c.title}</p><p className="text-xs text-[var(--muted)]">{c.source} · {new Date(c.collectedAt).toLocaleDateString("pt-BR")}</p></td><td>{formatBRL(c.priceCents+c.shippingCents)}</td><td><span className="badge">{c.priceType}</span></td><td>{c.condition.replaceAll("_"," ")}</td></tr>)}</tbody></table></div>}
      <form action={addComparable} className="mt-5 grid gap-3 border-t border-[var(--border)] pt-5 sm:grid-cols-3"><input type="hidden" name="opportunityId" value={id}/><div className="field sm:col-span-2"><label>Título *</label><input className="input" name="title" required/></div><div className="field"><label>Preço *</label><input className="input" name="price" inputMode="decimal" required/></div><div className="field"><label>Fonte *</label><select name="source"><option>Facebook Marketplace</option><option>OLX</option><option>Mercado Livre</option><option>Outra</option></select></div><div className="field"><label>URL</label><input className="input" name="url" type="url"/></div><div className="field"><label>Frete</label><input className="input" name="shipping" inputMode="decimal"/></div><div className="field"><label>Condição</label><select name="condition" defaultValue={item.condition}><option value="USADO_BOM">Usado — bom</option><option value="USADO_REGULAR">Usado — regular</option><option value="COM_DEFEITO">Com defeito</option><option value="NOVO">Novo</option></select></div><div className="field"><label>Tipo de preço</label><select name="priceType"><option value="ANUNCIADO">Anunciado</option><option value="VENDA_CONFIRMADA">Venda confirmada</option></select></div><div className="field"><label>Status</label><select name="status"><option value="ATIVO">Ativo</option><option value="REMOVIDO">Removido</option><option value="DESCONHECIDO">Desconhecido</option></select></div><div className="field"><label>Coletado em</label><input className="input" name="collectedAt" type="date" defaultValue={today} required/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="included" defaultChecked/> Incluir no cálculo</label><div className="sm:col-span-3"><button className="button">Adicionar comparável</button></div></form>
    </section>
  </div>;
}
