import Link from "next/link";
import { and, desc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { CopyNegotiation } from "@/components/copy-negotiation";
import { db } from "@/database/client";
import { attachments, auditLogs, marketComparables, opportunities, riskFlags } from "@/database/schema";
import { buyOpportunity } from "@/features/inventory/actions";
import { addComparable, duplicateOpportunity, toggleComparable } from "@/features/opportunities/actions";
import { addNegotiation, toggleFavorite, uploadAttachment } from "@/features/opportunities/extra-actions";
import { requireUser } from "@/lib/auth/session";
import { buildScenarios, maximumPurchasePrice, netRevenue } from "@/lib/finance/calculations";
import { getEffectivePriceGuide, getFavoriteIds } from "@/lib/local-settings";
import { formatBRL, formatPercent } from "@/lib/money";
import { evaluatePriceGuide } from "@/lib/price-guide";
import { detectProblems } from "@/lib/problem-detector";
import { recommend } from "@/lib/scoring/recommendation";
import { marketStatistics } from "@/lib/scoring/statistics";

const today = new Date().toISOString().slice(0, 10);

export default async function OpportunityDetail({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const item = await db.select().from(opportunities).where(and(eq(opportunities.id, id), eq(opportunities.userId, user.userId))).get();
  if (!item) notFound();

  const [comparables, flags, photos, negotiationLogs, favorites, effectiveGuide] = await Promise.all([
    db.select().from(marketComparables).where(eq(marketComparables.opportunityId, id)).all(),
    db.select().from(riskFlags).where(eq(riskFlags.opportunityId, id)).all(),
    db.select().from(attachments).where(and(eq(attachments.userId, user.userId), eq(attachments.entityType, "opportunity"), eq(attachments.entityId, id))).all(),
    db.select().from(auditLogs).where(and(eq(auditLogs.userId, user.userId), eq(auditLogs.entityType, "Opportunity"), eq(auditLogs.entityId, id), eq(auditLogs.action, "NEGOTIATION"))).orderBy(desc(auditLogs.occurredAt)).all(),
    getFavoriteIds(user.userId),
    getEffectivePriceGuide(user.userId),
  ]);

  const stats = marketStatistics(comparables);
  const purchasePrice = item.negotiatedPriceCents ?? item.askingPriceCents;
  const acquisition = { purchasePriceCents: purchasePrice, travelCents: item.travelCostCents, purchaseShippingCents: item.purchaseShippingCents, partsCents: item.partsCostCents, repairCents: item.repairCostCents, cleaningCents: item.cleaningCostCents, packagingCents: item.packagingCostCents, otherPurchaseCents: item.otherPurchaseCostsCents };
  const scenarios = buildScenarios(acquisition, stats, item.expectedDaysToSell);
  const probable = scenarios[1];
  const guide = evaluatePriceGuide({ ...item, askingPriceCents: purchasePrice }, effectiveGuide);
  const problems = detectProblems(`${item.title} ${item.notes ?? ""}`);
  const baseRecommendation = recommend({ comparableCount: stats.count, confidence: stats.confidence, roi: probable.roi, margin: probable.margin, riskLevel: item.riskLevel, repairRisk: item.condition === "COM_DEFEITO", fraudRisk: flags.some((flag) => flag.severity === "CRITICO") });
  const recommendation = guide.blockedReasons.length ? { label: "Não comprar" as const, reasons: guide.blockedReasons } : baseRecommendation;
  const additionalCosts = item.travelCostCents + item.purchaseShippingCents + item.partsCostCents + item.repairCostCents + item.cleaningCostCents + item.packagingCostCents + item.otherPurchaseCostsCents;
  const marketMax = maximumPurchasePrice(netRevenue({ salePriceCents: stats.medianCents }), additionalCosts, item.minimumProfitCents);
  const effectiveMax = stats.count ? (guide.adjustedBuyMaxCents ? Math.min(marketMax, guide.adjustedBuyMaxCents) : marketMax) : guide.adjustedBuyMaxCents;
  const initialOffer = effectiveMax ? Math.max(0, Math.round(effectiveMax * 0.9 / 100) * 100) : purchasePrice;
  const negotiationMessage = `Olá! Tenho interesse no ${item.title}. Considerando retirada rápida e pagamento à vista, consigo oferecer ${formatBRL(initialOffer)}. Se estiver tudo funcionando como descrito, podemos fechar?`;

  return <div className="grid gap-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/oportunidades" className="text-sm text-[var(--muted)]">← Oportunidades</Link><h1 className="mt-2 text-3xl font-black">{item.title}</h1><p className="mt-1 text-sm text-[var(--muted)]">{item.source} · {item.city}{item.neighborhood ? ` / ${item.neighborhood}` : ""} · {item.condition.replaceAll("_", " ")}</p></div><div className="flex flex-wrap gap-2"><form action={toggleFavorite}><input type="hidden" name="id" value={id}/><button className="button secondary">{favorites.includes(id) ? "★ Favorito" : "☆ Favoritar"}</button></form><Link className="button secondary" href={`/visita/${id}`}>Modo visita</Link>{item.originalUrl && <a className="button secondary" href={item.originalUrl} target="_blank" rel="noreferrer">Abrir original ↗</a>}<form action={duplicateOpportunity}><input type="hidden" name="id" value={id}/><button className="button secondary">Duplicar</button></form></div></header>

    {(flags.length > 0 || problems.length > 0) && <section className="rounded-2xl border border-orange-300 bg-orange-50 p-4 text-orange-950 dark:bg-orange-950/30 dark:text-orange-100"><h2 className="font-black">Problemas e sinais detectados</h2><ul className="mt-2 list-disc pl-5 text-sm">{problems.map((problem) => <li key={`${problem.label}-${problem.match}`}>{problem.label}: “{problem.match}”</li>)}{flags.map((flag) => <li key={flag.id}>{flag.description} — verifique antes de comprar.</li>)}</ul></section>}

    {guide.reference && <section className={`rounded-2xl border p-5 ${guide.blockedReasons.length ? "border-red-300 bg-red-50 dark:bg-red-950/20" : "border-lime/50 bg-lime/10"}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase text-[var(--muted)]">Sua tabela atual</p><h2 className="text-xl font-black">{guide.reference.model}</h2></div><Link className="button secondary" href="/referencias">Editar tabela</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-[var(--muted)]">Comprar até</p><p className="text-2xl font-black text-moss dark:text-lime">{formatBRL(guide.adjustedBuyMaxCents ?? guide.reference.buyMaxCents)}</p></div><div><p className="text-xs text-[var(--muted)]">Venda-base</p><p className="text-2xl font-black">{formatBRL(guide.reference.saleReferenceCents)}</p></div><div><p className="text-xs text-[var(--muted)]">Margem bruta-base</p><p className="text-2xl font-black">{formatBRL(guide.reference.saleReferenceCents - (guide.adjustedBuyMaxCents ?? guide.reference.buyMaxCents))}</p></div></div>{[...guide.blockedReasons, ...guide.warnings].length > 0 && <ul className="mt-3 list-disc pl-5 text-sm">{[...guide.blockedReasons, ...guide.warnings].map((message) => <li key={message}>{message}</li>)}</ul>}</section>}

    <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="panel p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Análise explicável</h2><span className="badge">{stats.confidence} CONFIANÇA</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{scenarios.map((scenario) => <article className={`rounded-xl border p-4 ${scenario.name === "Provável" ? "border-moss bg-green-50 dark:bg-green-950/20" : "border-[var(--border)]"}`} key={scenario.name}><p className="text-xs font-bold uppercase text-[var(--muted)]">{scenario.name}</p><p className="mt-2 text-xl font-black">{formatBRL(scenario.profitCents)}</p><p className="mt-1 text-sm">Venda: {formatBRL(scenario.salePriceCents)}</p><p className="text-sm">ROI: {formatPercent(scenario.roi)}</p><p className="text-sm">Margem: {formatPercent(scenario.margin)}</p></article>)}</div><div className="mt-5 rounded-xl bg-black/[.04] p-4 dark:bg-white/[.04]"><h3 className="font-black">{recommendation.label}</h3><ul className="mt-2 list-disc pl-5 text-sm text-[var(--muted)]">{recommendation.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div></div><aside className="panel p-5"><h2 className="text-xl font-black">Limites da compra</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-[var(--muted)]">Preço máximo recomendado</dt><dd className="text-2xl font-black text-moss dark:text-lime">{effectiveMax !== null ? formatBRL(effectiveMax) : "Aguardando dados"}</dd></div><div><dt className="text-[var(--muted)]">Capital necessário</dt><dd className="font-bold">{formatBRL(probable.costCents)}</dd></div><div><dt className="text-[var(--muted)]">Ponto de equilíbrio</dt><dd className="font-bold">{formatBRL(probable.breakEvenCents)}</dd></div></dl>{item.status === "EM_ANALISE" && <form action={buyOpportunity} className="mt-5 grid gap-3 border-t border-[var(--border)] pt-4"><input type="hidden" name="opportunityId" value={id}/><div className="field"><label>Preço final</label><input className="input" name="purchasePrice" defaultValue={(purchasePrice / 100).toFixed(2).replace(".", ",")} required/></div><div className="field"><label>Data</label><input className="input" name="purchasedAt" type="date" defaultValue={today} required/></div><div className="field"><label>Local no estoque</label><input className="input" name="location" placeholder="Prateleira A"/></div><button className="button">Registrar compra</button></form>}</aside></section>

    <section className="panel p-5"><h2 className="text-xl font-black">Assistente de negociação</h2><p className="mt-1 text-sm text-[var(--muted)]">Oferta inicial sugerida: {formatBRL(initialOffer)}. Ajuste livremente antes de enviar.</p><CopyNegotiation message={negotiationMessage}/><form action={addNegotiation} className="mt-5 grid gap-3 border-t border-[var(--border)] pt-4 sm:grid-cols-4"><input type="hidden" name="opportunityId" value={id}/><div className="field"><label>Data</label><input className="input" name="date" type="date" defaultValue={today}/></div><div className="field"><label>Tipo</label><select name="kind"><option>Oferta feita</option><option>Contraproposta</option><option>Preço final</option><option>Observação</option></select></div><div className="field"><label>Valor</label><input className="input" name="amount" inputMode="decimal"/></div><div className="field"><label>Observação</label><input className="input" name="note"/></div><button className="button sm:col-span-4">Salvar no diário</button></form>{negotiationLogs.length > 0 && <div className="mt-4 grid gap-2">{negotiationLogs.map((log) => { const data = JSON.parse(log.afterJson ?? "{}"); return <div key={log.id} className="rounded-xl border border-[var(--border)] p-3 text-sm"><b>{data.type}</b> · {new Date(log.occurredAt).toLocaleDateString("pt-BR")}{data.amountCents ? ` · ${formatBRL(data.amountCents)}` : ""}{data.notes ? ` — ${data.notes}` : ""}</div>; })}</div>}</section>

    <section className="panel p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Comparáveis de mercado</h2><p className="text-sm text-[var(--muted)]">{stats.count} selecionados · mediana {formatBRL(stats.medianCents)}</p></div><span className="text-xs text-[var(--muted)]">Preço anunciado ≠ venda confirmada</span></div>{comparables.length > 0 && <div className="mt-4 overflow-x-auto"><table><thead><tr><th>Usar</th><th>Anúncio</th><th>Preço</th><th>Tipo</th></tr></thead><tbody>{comparables.map((comparable) => <tr key={comparable.id}><td><form action={toggleComparable}><input type="hidden" name="id" value={comparable.id}/><input type="hidden" name="opportunityId" value={id}/><input type="hidden" name="included" value={String(comparable.included)}/><button className="button secondary py-1">{comparable.included ? "✓" : "—"}</button></form></td><td><p className="font-bold">{comparable.title}</p><p className="text-xs text-[var(--muted)]">{comparable.source}</p></td><td>{formatBRL(comparable.priceCents + comparable.shippingCents)}</td><td><span className="badge">{comparable.priceType}</span></td></tr>)}</tbody></table></div>}<form action={addComparable} className="mt-5 grid gap-3 border-t border-[var(--border)] pt-5 sm:grid-cols-3"><input type="hidden" name="opportunityId" value={id}/><div className="field sm:col-span-2"><label>Título *</label><input className="input" name="title" required/></div><div className="field"><label>Preço *</label><input className="input" name="price" inputMode="decimal" required/></div><div className="field"><label>Fonte *</label><select name="source"><option>Facebook Marketplace</option><option>OLX</option><option>Mercado Livre</option><option>Outra</option></select></div><div className="field"><label>URL</label><input className="input" name="url" type="url"/></div><div className="field"><label>Frete</label><input className="input" name="shipping" inputMode="decimal"/></div><div className="field"><label>Condição</label><select name="condition" defaultValue={item.condition}><option value="USADO_BOM">Usado — bom</option><option value="USADO_REGULAR">Usado — regular</option><option value="COM_DEFEITO">Com defeito</option><option value="NOVO">Novo</option></select></div><div className="field"><label>Tipo</label><select name="priceType"><option value="ANUNCIADO">Anunciado</option><option value="VENDA_CONFIRMADA">Venda confirmada</option></select></div><input type="hidden" name="status" value="ATIVO"/><input type="hidden" name="collectedAt" value={today}/><input type="hidden" name="included" value="on"/><div className="sm:col-span-3"><button className="button">Adicionar comparável</button></div></form></section>

    <section className="panel p-5"><h2 className="text-xl font-black">Fotos locais</h2><p className="mt-1 text-sm text-[var(--muted)]">Guarde estado, defeitos e número de série. As imagens ficam somente neste computador.</p><form action={uploadAttachment} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="entityType" value="opportunity"/><input type="hidden" name="entityId" value={id}/><input className="input max-w-md" type="file" name="file" accept="image/jpeg,image/png,image/webp" required/><button className="button">Guardar foto</button></form>{photos.length > 0 && <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map((photo) => <a href={`/api/attachments/${photo.id}`} target="_blank" key={photo.id}><img className="aspect-square w-full rounded-xl object-cover" src={`/api/attachments/${photo.id}`} alt={photo.fileName}/></a>)}</div>}</section>
  </div>;
}
