"use server";
import { randomUUID } from "node:crypto";
import fs from "node:fs";import path from "node:path";
import { and,eq } from "drizzle-orm";import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";
import { db } from "@/database/client";import { attachments,auditLogs,inspectionChecklists,inspectionResults,opportunities } from "@/database/schema";
import { requireUser } from "@/lib/auth/session";import { parseBulkListings } from "@/lib/bulk-capture";import { parseBRL } from "@/lib/money";import { toggleFavoriteId } from "@/lib/local-settings";
const value=(f:FormData,k:string)=>String(f.get(k)||"").trim();
export async function toggleFavorite(form:FormData){const user=await requireUser(),id=value(form,"id");if(!db.select({id:opportunities.id}).from(opportunities).where(and(eq(opportunities.id,id),eq(opportunities.userId,user.userId))).get())throw new Error("Oportunidade não encontrada");toggleFavoriteId(user.userId,id);revalidatePath(`/oportunidades/${id}`);revalidatePath("/favoritos")}
export async function addNegotiation(form:FormData){const user=await requireUser(),id=value(form,"opportunityId"),type=value(form,"type")||value(form,"kind"),amountCents=parseBRL(form.get("amount")),notes=value(form,"notes")||value(form,"note");if(!db.select({id:opportunities.id}).from(opportunities).where(and(eq(opportunities.id,id),eq(opportunities.userId,user.userId))).get())throw new Error("Oportunidade não encontrada");db.insert(auditLogs).values({id:randomUUID(),userId:user.userId,entityType:"Opportunity",entityId:id,action:"NEGOTIATION",afterJson:JSON.stringify({type,amountCents,notes}),occurredAt:new Date().toISOString()}).run();if(type==="ACEITA")db.update(opportunities).set({negotiatedPriceCents:amountCents,status:"NEGOCIACAO",updatedAt:new Date().toISOString()}).where(eq(opportunities.id,id)).run();revalidatePath(`/oportunidades/${id}`)}
export async function captureBulk(form:FormData){const user=await requireUser(),items=parseBulkListings(value(form,"listings")),now=new Date().toISOString();db.transaction(tx=>{for(const item of items){const id=randomUUID();tx.insert(opportunities).values({id,userId:user.userId,title:item.title,originalUrl:item.url,source:"Facebook Marketplace",category:item.category,model:item.model,condition:"USADO_BOM",askingPriceCents:item.priceCents,city:"Goiânia",capturedAt:now,status:"EM_ANALISE",riskLevel:"MEDIO",expectedDaysToSell:30}).run();}});redirect("/radar")}
export async function saveInspection(form:FormData){const user=await requireUser(),opportunityId=value(form,"opportunityId"),checklistId=value(form,"checklistId"),opportunity=db.select().from(opportunities).where(and(eq(opportunities.id,opportunityId),eq(opportunities.userId,user.userId))).get(),checklist=db.select().from(inspectionChecklists).where(eq(inspectionChecklists.id,checklistId)).get();if(!opportunity||!checklist)throw new Error("Inspeção inválida");const answers=Object.fromEntries(checklist.items.map((item,index)=>[item,form.get(`item-${index}`)==="on"?"OK":"PENDENTE"]));db.insert(inspectionResults).values({id:randomUUID(),opportunityId,checklistId,answers,completedAt:new Date().toISOString()}).run();revalidatePath(`/visita/${opportunityId}`)}
export async function uploadAttachment(form:FormData){const user=await requireUser(),entityType=value(form,"entityType"),entityId=value(form,"entityId"),file=form.get("file");if(!(file instanceof File)||!file.size)throw new Error("Selecione uma foto");if(file.size>4*1024*1024||!file.type.startsWith("image/"))throw new Error("Use uma imagem de até 4 MB");const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[file.type];if(!ext)throw new Error("Formato permitido: JPG, PNG ou WebP");const id=randomUUID(),dir=path.join(process.cwd(),"data","uploads");fs.mkdirSync(dir,{recursive:true});const storagePath=path.join(dir,`${id}.${ext}`);fs.writeFileSync(storagePath,Buffer.from(await file.arrayBuffer()));db.insert(attachments).values({id,userId:user.userId,entityType,entityId,fileName:file.name.slice(0,120),mimeType:file.type,sizeBytes:file.size,storagePath}).run();revalidatePath(entityType==="inventory"?`/estoque/${entityId}`:`/oportunidades/${entityId}`)}

